import { createHash, randomUUID } from "node:crypto";
import { patientCaseSchema, type CaseResourceAttributes, type MigrationPreview, type MigrationSession, type PatientCase } from "@modelforge/contracts";
import type { Pool, PoolClient } from "pg";
import type { TenantContext } from "../tenant-context.js";
import { insertAuditEntry, type AuditActor } from "./audit-store.js";
import { MigrationStateError, type CaseMigrationStore, type TenantCaseMigrationRepository } from "./case-migration-store.js";
import type { TenantCaseRepository } from "./case-store.js";

interface SessionRow { id: string; status: MigrationSession["status"]; source_fingerprint: string; total_items: number; accepted_items: number; preview: MigrationPreview | null; created_at: Date; updated_at: Date }
interface ItemRow { item_key: string; case_id: string; data: unknown; data_hash: string; status: MigrationPreview["items"][number]["status"]; errors: string[] }
interface ActiveRow { case_id: string; version: string; data: PatientCase; patient_id: string; owner_user_id: string; workspace_id: string | null; department_id: string | null; assigned_user_ids: string[]; active_consent_scopes: CaseResourceAttributes["activeConsentScopes"] }
const digest = (value: unknown): string => createHash("sha256").update(JSON.stringify(value)).digest("hex");
const schemaSql = (name: string): string => { if (!/^tenant_[a-f0-9]{32}$/.test(name)) throw new Error("Unsafe tenant schema identifier."); return `"${name}"`; };
const mapSession = (row: SessionRow, organizationId: string): MigrationSession => ({ id: row.id, organizationId, status: row.status, sourceFingerprint: row.source_fingerprint, totalItems: row.total_items, acceptedItems: row.accepted_items, preview: row.preview ?? undefined, createdAt: row.created_at.toISOString(), updatedAt: row.updated_at.toISOString() });

export class PostgresCaseMigrationStore implements CaseMigrationStore {
    constructor(private readonly pool: Pool) {}
    forTenant(context: TenantContext, _cases: TenantCaseRepository): TenantCaseMigrationRepository {
        const schema = schemaSql(context.schemaName);
        return {
            start: (input, actor) => this.start(context,schema,input,actor),
            get: (id) => this.get(context,schema,id),
            upload: (id,items,actor) => this.upload(context,schema,id,items,actor),
            validate: (id,actor) => this.validate(context,schema,id,actor),
            activate: (id,actor) => this.activate(context,schema,id,actor),
            rollback: (id,actor) => this.rollback(context,schema,id,actor),
        };
    }
    private async begin(client: PoolClient, context: TenantContext): Promise<void> { await client.query("BEGIN"); await client.query("SELECT set_config('app.tenant_id',$1,true)",[context.organizationId]); }
    private async get(context: TenantContext, schema: string, id: string): Promise<MigrationSession | null> { const result = await this.pool.query<SessionRow>(`SELECT * FROM ${schema}.case_migrations WHERE id=$1`,[id]); return result.rows[0] ? mapSession(result.rows[0],context.organizationId) : null; }
    private async start(context: TenantContext, schema: string, input: { sourceFingerprint: string; totalItems: number }, actor: AuditActor): Promise<MigrationSession> {
        // The conflict target is (source_fingerprint, created_by), not
        // source_fingerprint alone — see migrations/022_case_migration_fingerprint_scope.sql.
        // A bare source_fingerprint key means any two org members (or the
        // same user across two separate attempts, since sha256("[]") is
        // identical every time for someone with zero local cases) who stage
        // with identical local case content collide onto the exact same
        // session, silently handing the second caller a session — possibly
        // already validated or activated — that they never started and that
        // their own client's Activate button won't recognize as theirs.
        const client=await this.pool.connect(); try { await this.begin(client,context); const now=new Date(); const result=await client.query<SessionRow>(`INSERT INTO ${schema}.case_migrations (id,status,source_fingerprint,total_items,accepted_items,created_by,created_at,updated_at) VALUES ($1,'staging',$2,$3,0,$4,$5,$5) ON CONFLICT (source_fingerprint, created_by) DO UPDATE SET source_fingerprint=EXCLUDED.source_fingerprint RETURNING *`,[randomUUID(),input.sourceFingerprint,input.totalItems,actor.userId,now]); await insertAuditEntry(client,{organizationId:context.organizationId,actorUserId:actor.userId,actorExternalSubject:actor.externalSubject,action:"caseMigration.start",targetType:"caseMigration",targetId:result.rows[0].id}); await client.query("COMMIT"); return mapSession(result.rows[0],context.organizationId); } catch(e){await client.query("ROLLBACK");throw e;} finally{client.release();}
    }
    private async upload(context: TenantContext, schema: string, id: string, items: { itemKey:string;patientCase:unknown }[], actor: AuditActor): Promise<MigrationSession> {
        const client=await this.pool.connect(); try { await this.begin(client,context); const session=await client.query<SessionRow>(`SELECT * FROM ${schema}.case_migrations WHERE id=$1 FOR UPDATE`,[id]); if(!session.rows[0]) throw Object.assign(new Error("Migration not found."),{statusCode:404}); if(session.rows[0].status!=="staging") throw new MigrationStateError("Migration is not accepting batches.");
            for(const item of items){ const hash=digest(item.patientCase); const parsed=patientCaseSchema.safeParse(item.patientCase); const caseId=parsed.success?parsed.data.id:(typeof (item.patientCase as {id?:unknown})?.id==="string"?(item.patientCase as {id:string}).id:item.itemKey); const existing=await client.query<{data_hash:string}>(`SELECT data_hash FROM ${schema}.case_migration_items WHERE migration_id=$1 AND item_key=$2`,[id,item.itemKey]); if(existing.rows[0]&&existing.rows[0].data_hash!==hash) throw new MigrationStateError(`Item key ${item.itemKey} was reused with different data.`); await client.query(`INSERT INTO ${schema}.case_migration_items (migration_id,item_key,case_id,data,data_hash,status,errors) VALUES ($1,$2,$3,$4,$5,'pending','[]') ON CONFLICT DO NOTHING`,[id,item.itemKey,caseId,JSON.stringify(item.patientCase),hash]); }
            await client.query(`UPDATE ${schema}.case_migrations SET updated_at=$2 WHERE id=$1`,[id,new Date()]); await insertAuditEntry(client,{organizationId:context.organizationId,actorUserId:actor.userId,actorExternalSubject:actor.externalSubject,action:"caseMigration.upload",targetType:"caseMigration",targetId:id,details:{itemCount:items.length}}); await client.query("COMMIT"); return (await this.get(context,schema,id))!; } catch(e){await client.query("ROLLBACK");throw e;} finally{client.release();}
    }
    private async validate(context: TenantContext, schema: string, id: string, actor: AuditActor): Promise<MigrationPreview> {
        const client=await this.pool.connect(); try { await this.begin(client,context); const session=await client.query<SessionRow>(`SELECT * FROM ${schema}.case_migrations WHERE id=$1 FOR UPDATE`,[id]); if(!session.rows[0]) throw Object.assign(new Error("Migration not found."),{statusCode:404}); if(!["staging","validated"].includes(session.rows[0].status)) throw new MigrationStateError("Migration cannot be validated in its current state."); const items=await client.query<ItemRow>(`SELECT * FROM ${schema}.case_migration_items WHERE migration_id=$1 ORDER BY item_key`,[id]); const previewItems:MigrationPreview["items"]=[];
            for(const item of items.rows){ const parsed=patientCaseSchema.safeParse(item.data); let status:ItemRow["status"]; let errors:string[]; let caseId=item.case_id; if(!parsed.success){status="invalid";errors=parsed.error.issues.map(issue=>`${issue.path.join(".")}: ${issue.message}`);} else {caseId=parsed.data.id; const collision=await client.query(`SELECT 1 FROM ${schema}.patient_cases WHERE case_id=$1 AND active=TRUE`,[caseId]); status=collision.rowCount?"collision":"accepted";errors=status==="collision"?["A case with this id already exists in the destination tenant."]:[];} await client.query(`UPDATE ${schema}.case_migration_items SET case_id=$3,status=$4,errors=$5 WHERE migration_id=$1 AND item_key=$2`,[id,item.item_key,caseId,status,JSON.stringify(errors)]); previewItems.push({caseId,status,errors}); }
            const preview:MigrationPreview={total:items.rows.length,valid:previewItems.filter(i=>i.status==="accepted").length,invalid:previewItems.filter(i=>i.status==="invalid").length,collisions:previewItems.filter(i=>i.status==="collision").length,items:previewItems}; await client.query(`UPDATE ${schema}.case_migrations SET status='validated',accepted_items=$2,preview=$3,updated_at=$4 WHERE id=$1`,[id,preview.valid,JSON.stringify(preview),new Date()]); await insertAuditEntry(client,{organizationId:context.organizationId,actorUserId:actor.userId,actorExternalSubject:actor.externalSubject,action:"caseMigration.validate",targetType:"caseMigration",targetId:id,details:{valid:preview.valid,invalid:preview.invalid,collisions:preview.collisions}}); await client.query("COMMIT"); return preview; } catch(e){await client.query("ROLLBACK");throw e;} finally{client.release();}
    }
    private async next(client:PoolClient,schema:string):Promise<string>{const result=await client.query<{assigned:string}>(`UPDATE ${schema}.case_change_counter SET next_sequence=next_sequence+1 WHERE singleton=TRUE RETURNING next_sequence-1 AS assigned`);return result.rows[0].assigned;}
    private async activate(context:TenantContext,schema:string,id:string,actor:AuditActor):Promise<MigrationSession>{const client=await this.pool.connect();try{await this.begin(client,context);const session=await client.query<SessionRow>(`SELECT * FROM ${schema}.case_migrations WHERE id=$1 FOR UPDATE`,[id]);const row=session.rows[0];if(!row)throw Object.assign(new Error("Migration not found."),{statusCode:404});if(row.status!=="validated"||!row.preview||row.preview.invalid>0||row.preview.collisions>0||row.accepted_items!==row.total_items)throw new MigrationStateError("Migration must be complete and valid before activation.");const items=await client.query<ItemRow>(`SELECT * FROM ${schema}.case_migration_items WHERE migration_id=$1 AND status='accepted' ORDER BY item_key`,[id]);
            // The preview's "0 collisions" was computed at the last validate()
            // call, over a completely separate table (patient_cases) that the
            // ordinary case-creation route can write to at any time in
            // between — the FOR UPDATE lock above only serializes concurrent
            // callers of this same migration, it can't see a live case being
            // created out from under it. Re-check right before inserting so
            // that gap surfaces as a clean, actionable error instead of a
            // raw primary-key violation, and so activation never partially
            // applies a batch it can't fully complete: either every item
            // lands, or (thanks to the transaction around this whole method)
            // none do.
            if(items.rows.length){const liveCollisions=await client.query<{case_id:string}>(`SELECT case_id FROM ${schema}.patient_cases WHERE active=TRUE AND case_id = ANY($1)`,[items.rows.map(i=>i.case_id)]);if(liveCollisions.rowCount)throw new MigrationStateError(`Destination changed since validation: ${liveCollisions.rowCount} case id(s) now collide (e.g. "${liveCollisions.rows[0].case_id}"). Re-run validate and retry activation.`);}
            for(const item of items.rows){const patientCase=patientCaseSchema.parse(item.data);const version=await this.next(client,schema);const now=new Date();const saved={...patientCase,version,updatedAt:now.toISOString()};const resource:CaseResourceAttributes={organizationId:context.organizationId,caseId:saved.id,patientId:saved.patientId??saved.id,ownerUserId:actor.userId!,workspaceId:saved.workspaceId,departmentId:saved.departmentId,assignedUserIds:saved.assignedUserIds??[],activeConsentScopes:saved.consentRecords.filter(r=>!r.revokedAt).map(r=>r.scope)};
                try{await client.query(`INSERT INTO ${schema}.patient_cases (case_id,version,data,patient_id,owner_user_id,workspace_id,department_id,assigned_user_ids,active_consent_scopes,staged_migration_id,active,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,TRUE,$11)`,[saved.id,version,JSON.stringify(saved),resource.patientId,resource.ownerUserId,resource.workspaceId??null,resource.departmentId??null,resource.assignedUserIds,resource.activeConsentScopes,id,now]);}catch(e){if((e as {code?:string}).code==="23505")throw new MigrationStateError(`Destination changed since validation: case id "${saved.id}" now collides. Re-run validate and retry activation.`);throw e;}
                await client.query(`INSERT INTO ${schema}.case_changes (sequence,kind,case_id,version,patient_case,resource,changed_at) VALUES ($1,'upsert',$2,$1,$3,$4,$5)`,[version,saved.id,JSON.stringify(saved),JSON.stringify(resource),now]);}
            await client.query(`UPDATE ${schema}.case_migrations SET status='active',updated_at=$2 WHERE id=$1`,[id,new Date()]);await insertAuditEntry(client,{organizationId:context.organizationId,actorUserId:actor.userId,actorExternalSubject:actor.externalSubject,action:"caseMigration.activate",targetType:"caseMigration",targetId:id});await client.query("COMMIT");return (await this.get(context,schema,id))!;}catch(e){await client.query("ROLLBACK");throw e;}finally{client.release();}}
    private async rollback(context:TenantContext,schema:string,id:string,actor:AuditActor):Promise<MigrationSession>{const client=await this.pool.connect();try{await this.begin(client,context);const session=await client.query<SessionRow>(`SELECT * FROM ${schema}.case_migrations WHERE id=$1 FOR UPDATE`,[id]);if(!session.rows[0])throw Object.assign(new Error("Migration not found."),{statusCode:404});if(session.rows[0].status!=="active")throw new MigrationStateError("Only an active migration can be rolled back.");const active=await client.query<ActiveRow>(`SELECT * FROM ${schema}.patient_cases WHERE staged_migration_id=$1 AND active=TRUE FOR UPDATE`,[id]);for(const row of active.rows){const version=await this.next(client,schema);const now=new Date();const resource:CaseResourceAttributes={organizationId:context.organizationId,caseId:row.case_id,patientId:row.patient_id,ownerUserId:row.owner_user_id,workspaceId:row.workspace_id??undefined,departmentId:row.department_id??undefined,assignedUserIds:row.assigned_user_ids,activeConsentScopes:row.active_consent_scopes};await client.query(`UPDATE ${schema}.patient_cases SET active=FALSE,version=$2,updated_at=$3 WHERE case_id=$1`,[row.case_id,version,now]);await client.query(`INSERT INTO ${schema}.case_changes (sequence,kind,case_id,version,patient_case,resource,changed_at) VALUES ($1,'delete',$2,$1,NULL,$3,$4)`,[version,row.case_id,JSON.stringify(resource),now]);}await client.query(`UPDATE ${schema}.case_migrations SET status='rolled-back',updated_at=$2 WHERE id=$1`,[id,new Date()]);await insertAuditEntry(client,{organizationId:context.organizationId,actorUserId:actor.userId,actorExternalSubject:actor.externalSubject,action:"caseMigration.rollback",targetType:"caseMigration",targetId:id});await client.query("COMMIT");return (await this.get(context,schema,id))!;}catch(e){await client.query("ROLLBACK");throw e;}finally{client.release();}}
}
